server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 8MB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    instance:

fdfs:
  so-timeout: 2000 # 超时时间
  connect-timeout: 2000 # 连接超时时间
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址：你的虚拟机服务器地址+端口（默认是22122）
    - 8.142.116.136:22122